baseURL = "http://sonickenbaker.github.io/"
languageCode = "en-us"
title = "My Personal Website"
theme = "zen"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"

  [[menu.main]]
    name = "posts"
    url = "/posts/"